name: dokuwiki

services:
  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: dokuwiki_msmtpd
    env_file:
      - "./msmtpd.env"
    environment:
      - "TZ"
    restart: always

  dokuwiki:
    image: crazymax/dokuwiki:latest
    container_name: dokuwiki
    depends_on:
      - msmtpd
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    volumes:
      - "./data:/data"
    env_file:
      - "./dokuwiki.env"
    environment:
      - "TZ"
      - "PUID"
      - "PGID"
    restart: always
